# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network", type: "dhcp"
  # config.vm.network "forwarded_port", guest: 9090, host: 9090
  # config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = 1
    vb.name = "Prometheus"
  end
  config.vm.provision "file", source: "../prometheus-discovery/avahi-discover.sh", destination: "/home/vagrant/avahi-discover.sh"
  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.provision :shell, inline: <<-EOF
    echo "Prometheus is available on http://$(hostname -I | awk '{print \$2}'):9090"
  EOF
end
